# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 234783129fda2f9b33c5709e785c2c0fb91ded82c9b7c6e5d38a5677ebab2611976ef488278b9cdfae5055102fc5a4cd2b1868f4fda694583abc7bc4d0081232

test:
  secret_key_base: 72c074e73723a986a1204c7fdac5a2e9a7034f6252dc5ebb421d960066088a32ce36aac0a9972af1a3c042fe29f81280ac0f438ff4cd7df2d8c57cd13b09c032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
